= DIY Media Player Box - Backend

This is a small application which turns any Raspberry Pi in a music box.

My target was to build a DIY Music Box for small children. (Like the Toniebox)

This is the main repository which merges the backend and the ui. (ui as a submodule)

== Preparation

You need:

* NodeJS >= 10.23
* If you use a HifiBerry DAC zero, see here: https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/

If you are testing the backend, you should create a `.env` file in the root dir.

The content could look like:

[source,bash]
----
PORT=8080
UI_CONTENT_PATH=ui/public
HTTP_REQUEST_SIZE_LIMIT=60mb
ALLOW_ALL_ORIGIN=false
----

Here is a short description:

|===
|Name                       |Default value                  |Description

|PORT                       |8080                           |The port the application server is listening on.
|UI_CONTENT_PATH            |Application root + 'ui/public' |Points to the path where the UI content is located.
|HTTP_REQUEST_SIZE_LIMIT    |30mb                           |The maximum http request header size (must end with 'mb')
|ALLOW_ALL_ORIGIN           |false                          |If you are running the backend and the ui on different ports, you need to enable this to be able to access the backend API. (Should be used only for testing. UI content is served by the application server usually.)
|===

You can also define these as usual environment variables. (export ...)

== Before you start

I tested this on a Raspberry PI (3 and Zero) and the audio preview in the browser.

NOTE: You cannot compile the UI on a Raspberry Pi Zero due to lack of memory (512 MB)

So you will have to compile it elsewhere and copy it to the Pi Zero. Here you can use the `UI_CONTENT_PATH` variable.

== Init submodule (UI)
Load (aka clone) the content of the UI repository.

To do so, run `git submodule update --init --recursive`

== Install dependencies backend
Install all necessary libraries for the backend part.

Run `npm install`

== Install dependencies UI

NOTE: Not working on the Raspberry Pi Zero (See 'Before you start')

Install all necessary libraries for the UI part. (Needed to build the UI).

Run `npm run ui-init`

== Build UI

NOTE: Not working on the Raspberry Pi Zero (See 'Before you start')

Build the UI part.

Run `npm run ui-build`

== Run it
If the `UI_CONTENT_PATH` environment variable is not changed, start the server with

 `npm start`
