= DIY Media Player Box

This is a small application which turns any Raspberry Pi in a music box.

My target was to build a DIY Music Box for small children. (Like the Toniebox)

== Preparation

You need:

* Taskfile on local machine -> https://taskfile.dev/
* Ansible -> https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-and-upgrading-ansible
* NodeJS >= 10.23 to build the UI -> https://nodejs.org/en/download/
* A running MQTT broker on the raspi (like mosquitto -> `apt install mosquitto`)
* If you use a HifiBerry DAC zero, see here: https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/

You need to create a `.env` file in the root dir. (Copy `.env.dist` and adjust settings)
The assumption is, that the default Raspian user (Pi) is used.

The content:

[source,bash]
----
REMOTE_SERVER=<ip_address_of_pi>
RASPBERRY_PASSWORD=<password_of_pi_user>
----

== Before you start

I tested this on a Raspberry Pi Zero and the audio preview in the browser.

NOTE: You cannot compile the UI on a Raspberry Pi Zero due to lack of memory (512 MB)

== How to use / deploy it

=== The Taskfile

The Taskfile has everything you need to make it run on the Pi. Here are the tasks to accomplish this:

|===
|Task name                       |Description
|setupTarget | If the Raspberry was freshly set up, use this to prepare the Pi for all compile tasks (install golang and some dev-dependencies)
|compileRfidReader | Copy the rfid-reader folder to the raspi, compile it and copy the compiled artifact to the Pi's home folder
|compileController | Copy the controller folder to the raspi, compile it and copy the compiled artifact to the Pi's home folder
|compileAudioPlayer | Copy the audio-player folder to the raspi, compile it and copy the compiled artifact to the Pi's home folder
|compileAll | Execute the tasks "compileRfidReader", "compileController" and "compileAudioPlayer" at once
|compileUi | Build and package the UI and copy the result to the controller folder (into "ui" folder)
|copyUi | Copy the ui from controller folder to the raspi into the Pi's home folder
|===

=== Order of operation

* Call `setupTarget` once when you have a fresh Raspberry Pi set up
* Call `compileAll` to compile all binaries (it may take some time on the raspi zero...)
* Call `compileUi` to build the ui
* Call `copyUi` to copy the ui to the raspi. You have to do this, otherwise you will get an error message, when you start the controller and try to access the web interface

=== Autostart on Raspi

=== Others

Everything will be compiled on the Raspi, because te local compile is not working for some reason. I get a "Segmentation Fault" for controller and audio-player. Rfid-reader is working fine.
The current state is located in the folder: local-compile
