version: '3'

dotenv: ['.env']

tasks:
  setupTarget:
    desc: Initial setup on target machine (Install go and alsa dev dependencies)
    dir: ansible
    cmds:
      - sshpass -p "$RASPBERRY_PASSWORD" ansible-playbook -i $REMOTE_SERVER, playbook-setup-target.yml --ask-pass

  compileProject:
    dir: ansible
    cmds:
      - sshpass -p "$RASPBERRY_PASSWORD" ansible-playbook -i $REMOTE_SERVER, playbook-compile-on-target.yml --ask-pass

  default:
    cmds:
      - go-task -l
    silent: true
