- name: "Setup Target"
  hosts: all
  remote_user: pi

  tasks:
    - name: Compile components
      include_tasks: partial/compile-component.yml
      vars:
        component_name: "{{ item }}"
        tag_name: "{{ item }}"
      loop:
        - "rfid-reader"
        - "controller"
        - "audio-player"
        - "io-controller"
      tags:
        - backend

    - name: Copy UI to target
      copy:
        src: ../controller/ui
        dest: "/home/pi/"

      tags:
        - ui
