- name: "Setup Target"
  hosts: all

  tasks:
    - name: Ensure "archives" folder exists
      file:
        path: "../archives"
        state: directory
      delegate_to: localhost
      tags:
        - backend

    - name: Copy config file to target
      copy:
        src: config/config.yaml
        dest: "/home/pi/"
      tags:
        - backend
        - config
      register: output_config

    - name: Terminate all, when config changed
      shell:
        cmd: ./terminateAll.sh
      tags:
        - backend
        - config
      when: output_config.changed

    - name: Compile components
      include_tasks: partial/compile-component.yml
      vars:
        component_name: "{{ item }}"
        tag_name: "{{ item }}"
      loop:
        - "rfid-reader"
        - "controller"
        - "audio-player"
        - "io-controller"
        - "logger"
        - "monitor"
      tags:
        - backend

    - name: Copy UI to target
      copy:
        src: ../controller/ui
        dest: "/home/pi/"
      tags:
        - ui
